site_name: 冰焰博客站
site_url: https://maxiceflame.github.io/MaxIceFlameDatabase/
site_author: Max冰焰
theme:
  name: material
  favicon: img/favicon.ico
  logo: img/pic1.png
  language: zh
  features:
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.instant.prefetch
    - navigation.instant.progress
    - toc.follow
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: 夜间模式
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 日间模式
nav:
  - 主页:
      - {"首页":"index.md"}
      - 跳舞的线:
        - {"管理条例":"regulation.md"}
        - {"饭制模板":"template.md"}
        - {"模板手册":"tutorial.md"}
        - {"相机跟随":"following.md"}
      - 其他:
        - {"老八汉堡店":"burger.md"}
        - {"电子木鱼":"fish.md"}
  - MaxLine Wiki:
      - {"介绍":"ml_wiki/intro.md"}
      - {"关卡":"ml_wiki/level.md"}
      - {"皮肤":"ml_wiki/skin.md"}
      - {"成就":"ml_wiki/achievement.md"}
      - {"日志":"ml_wiki/update.md"}
      - {"关于":"ml_wiki/about.md"}
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
extra:
  generator: false
  social:
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/89919399
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@maxiceflame_naheeda
plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: zh
          default: true
          name: 中文
          build: true
        - locale: en
          name: English
          build: true
          nav_translations:
            主页: Home
            首页: Home
            跳舞的线: Dancing Line
            管理条例: Regulations
            饭制模板: DLFM Template
            模板手册: Template User Manual
            相机跟随: Camera Follow
            介绍: Introduction
            关卡: Levels
            皮肤: Skins
            成就: Achievements
            日志: Change Logs
            关于: About
            其他: Other
            电子木鱼: Electronic Wooden Fish
            老八汉堡店: Laoba's Burger Restaurant
          site_name: MaxIceFlame's Blog
          site_author: MaxIceFlame
  - git-revision-date-localized